name: flutter_app_chat
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.6.0
  cupertino_icons: 1.0.8
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0
  country_picker: ^2.0.23
  rounded_loading_button: ^2.1.0
  provider: ^6.1.2
  lottie: ^2.7.0
  shared_preferences: ^2.2.3
  pinput: ^5.0.0
  google_fonts: 6.1.0
  image_picker: ^1.0.5
  image_cropper: ^5.0.1
  uuid: ^4.2.2
  date_format: ^2.0.9
  grouped_list: ^6.0.0
  swipe_to: ^1.0.6
  timeago: ^3.7.0
  cached_network_image: ^3.3.1
  flutter_sound_record: ^3.3.2
  permission_handler: ^11.0.1
  audioplayers: ^5.2.1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Image_personal.png
    - assets/loties/
