// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf340ppzH1OZ8wUb2k8JPys5sjzMxI7-E',
    appId: '1:819698376687:web:75e21ee2bb59518ec9201a',
    messagingSenderId: '819698376687',
    projectId: 'flutterchatapp-c11e4',
    authDomain: 'flutterchatapp-c11e4.firebaseapp.com',
    storageBucket: 'flutterchatapp-c11e4.appspot.com',
    measurementId: 'G-61G14BLZV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkum2o5SDCizhFU5Vok3Gz4lTQThyaYIY',
    appId: '1:819698376687:android:be6f757b3fd3e7edc9201a',
    messagingSenderId: '819698376687',
    projectId: 'flutterchatapp-c11e4',
    storageBucket: 'flutterchatapp-c11e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVhH0xOICsjE87ssmIfXgDSB6wy6P0vH4',
    appId: '1:819698376687:ios:4e864e7550bdb7c6c9201a',
    messagingSenderId: '819698376687',
    projectId: 'flutterchatapp-c11e4',
    storageBucket: 'flutterchatapp-c11e4.appspot.com',
    iosBundleId: 'com.hoangphuc.flutterappchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD89SCcfU1TJpGmSiSyVNdKlZmgMVWoJco',
    appId: '1:990981149661:web:920ae3188d4cc420e95c34',
    messagingSenderId: '990981149661',
    projectId: 'flutterappchat-10d62',
    authDomain: 'flutterappchat-10d62.firebaseapp.com',
    storageBucket: 'flutterappchat-10d62.appspot.com',
    measurementId: 'G-LRQQE33JP6',
  );
}